role_name							= "proteus-redshift-scheduler-dev"
iam_role_desc						= "Grant access to redshift Dev"
role_tags							= {
       "ApplicationName"    = "Proteus"
       "Department"         = "PTS"
       "CostCenter"         = "FMG"
	   "BackupPlan"         = "None"
       "TechStack"          = "AWS"
       "Automated"          = "True"
       "CreatedBy"          = "mfaizudeen"
	   "DataClassification" = "Low"
       "Infrastructure"     = "False"
       "Usage"              = "Project"
       "Version"            = "1.0"
	   "CreatedOn"		    = "05182023"
	   "LastUpdated"        = "05182023"
    }
proteus-redshift-scheduler		    = true
proteus-redshift-scheduler_arn	    = "arn:aws:iam::116762271881:policy/proteus-redshift-scheduler"