domain_name = "marketingservices-athena-ui.franklinmadisonds.com"
validation = "DNS"
tags = {
    "ApplicationName"		= "AthenaNextgen2.0"
	"Automated"				= "True"
	"BackupPlan"			= "None"
	"CostCenter"			= "FMG"
	"CreatedBy"				= "DevOps"
	"CreatedOn"				= "09192024"
	"DataClassification"	= "DR"
	"Department"			= "ANG2"
	"Infrastructure"		= "False"
	"LastUpdated"			= "09192024"
	"TechStack"				= "AWS"
	"Usage"					= "Project"
	"Version"				= "1.0"
    }