bucket_short_name = "insclaimsbockserver"
environment = "dev"
logging_bucket_name =  "franklin-dev-s3-access-logs"
logging_bucket_base_prefix = "insclaimsbockserver-dev"
acl                 = "private"
tags ={
    "ApplicationName"		= "Lasso"
	"Automated"				= "True"
	"BackupPlan"			= "None"
	"CreatedBy"				= "bmukesh"
	"CreatedOn"				= "10072022"
	"CostCenter"			= "FMG"
	"DataClassification"	= "None"
	"Department"			= "LSO"
	"Infrastructure"		= "False"
	"LastUpdated"			= "06262023"
	"TechStack"				= "AWS"
	"Usage"					= "Project"
	"Version"				= "1.0"
}
insclaimsbockserver_policy = true
allowed_read_only_user_list = ["arn:aws:iam::894891841990:user/InsuranceClaimsBockServer-LassoBiz-UserNonProd"]
s3_enable_lifecycle_config = true
s3_lifecycle_days = 30