iam_policy_name				= "lasso-secrets-manager-policy-dr"
iam_policy_tags				= {
	"ApplicationName" = "Lasso"
	"Automated" = "True"
	"BackupPlan" = "None"
	"CostCenter" = "FMG"
	"CreatedBy" = "mfaizudeen"
	"CreatedOn" = "02202023"
	"DataClassification" = "Low"
	"Department" = "LSO"
	"Infrastructure" = "False"
	"LastUpdated" = "02202023"
	"TechStack" = "AWS"
	"Usage" = "Project"
	"Version" = "1.0"
    }
lasso_secrets_mgr_policy	= "true"
iam_policy_desc				= "Lasso Access Secret Manager DR"