role_name = "marketing-vanity-lambda-role-dev"
policy_name = "marketing-vanity-lambda-policy"
role_tags = {
	"Department": "MKT"
	"LastUpdated": "05182024"
	"CostCenter": "FMG"
	"CreatedOn": "05182024"
	"DataClassification": "None"
	"Infrastructure": "False"
	"Usage":"Project"
	"Version": "1.0"
	"ApplicationName": "Marketing"
	"TechStack": "AWS"
	"Automated": "True"
	"BackupPlan": "None"
	"CreatedBy": "DevOps"
}
marketing-vanity-lambda-policy = true
s3_bucket_name = "marketing-vanity-automation-dev"
secrets_name = "marketing-vanity-secrets-dev"