lambda_function_name = "marketingservice-api-refreshtoken-qa"
role = "arn:aws:iam::634621569833:role/marketing-lambda-role-qa"
description = "This is a refresh token call for marketing service"
env_variables = {
		"BLOB" = "AQICAHhpgarfAJGNwCu+nUEpfEs98L3ScPojfJgQYQaUajUohQHRqy6J3FZ+fc8QNvPQlW0kAAAAfTB7BgkqhkiG9w0BBwagbjBsAgEAMGcGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMGVEdPE9gUKUKjWjtAgEQgDoNqtite5K9Tpd80ct3kvou97CBMB5ieQY5hvzID95GK6ltilN7rjUTIpy3IeItaInhYbtEAPy2ET8D"
		"LOGGER" = "DEBUG"
	}
tags = {
	"ApplicationName" = "Marketing"
	"Automated" = "True"
	"BackupPlan" = "None"
	"CostCenter" = "FMG"
	"CreatedBy" = "DevOps"
	"CreatedOn" = "09022024"
	"DataClassification" = "Low"
	"Department" = "MKT"
	"Infrastructure" = "False"
	"LastUpdated" = "09022024"
	"TechStack" = "NodeJS"
	"Usage" = "Project"
	"Version" = "1.0"
	}
memory_size = 512
timeout = 15
subnets = ["subnet-059a28296ee46f82f","subnet-0aeea9e95e8137ce8"]
security_groups = ["sg-0e0bde4366d2b3a7d"]
reserved_concurrent_executions = -1
publish = false
runtime = "nodejs20.x"
handler = "marketingservice-api-refreshtoken.handler"
filename = "js/marketingservice-api-refreshtoken.zip"
package_type = "Zip"
source_code_hash = "js/marketingservice-api-refreshtoken.zip"