iam_policy_name			= "digital-logger-policy-dev"
iam_policy_tags			= {
		"Department": "DGT"
        "LastUpdated": "04222024"
        "CostCenter":  "FMG"
        "CreatedOn": "04032024"
        "DataClassification": "Low"
        "Infrastructure": "False"
        "Usage":"Project"
        "Version": "1.0"
        "ApplicationName": "Digital"
        "TechStack": "None"
        "Automated": "True"
        "BackupPlan": "None"
        "CreatedBy": "DevOps"
    }
digital_logger_policy		= "true"
digital_log_group_arn		= "arn:aws:logs:us-east-1:116762271881:*"
iam_policy_desc				= "Digital Logger Policy Dev"