domain_name = "dev-dashboard-mt.franklinmadisonds.com"
validation = "DNS"
tags = {
        "Department": "DSB"
		"LastUpdated": "06202024"
		"CostCenter": "FMG"
		"CreatedOn": "06202024"
		"DataClassification": "Low"
		"Infrastructure": "False"
		"Usage": "Project"
		"Version": "1.0"
		"ApplicationName": "DashBoard"
		"TechStack": "None"
		"Automated": "True"
		"BackupPlan": "None"
		"CreatedBy": "DevOps"
    }