iam_user_name			= "lasso-mailinduct-user-stage"
iam_user_tags			= {
		"Department": "LSO"
		"LastUpdated": "06152023"
		"CostCenter": "FMG"
		"CreatedOn": "05232023"
		"DataClassification": "Low"
		"Infrastructure": "False"
		"Usage": "Project"
		"Version": "1.0"
		"ApplicationName": "Lasso"
		"TechStack": "None"
		"Automated": "True"
		"BackupPlan": "None"
		"CreatedBy": "sbose"
    }
iam_policy_name			= "arn:aws:iam::702230634984:policy/lasso-kms-policy-stage"
lasso_kms_policy		= "true"