module "rds-proxy" {
	source				= "../../../modules/rds_proxy/"
	secret_name			= var.secret_name
	secret_description	= var.secret_description
	secret_rc_window	= var.secret_rc_window
	secret_tags			= var.secret_tags
	secret_values	= var.secret_values
	sg_name				= var.sg_name
	sg_description		= var.sg_description
	sg_vpc_id			= var.sg_vpc_id
	sg_ingress_rules	= var.sg_ingress_rules
	sg_tags				= var.sg_tags
	rds_proxy_name				= var.rds_proxy_name
	rds_proxy_debug_logging		= var.rds_proxy_debug_logging
	rds_proxy_engine			= var.rds_proxy_engine
	rds_proxy_idle_timeout		= var.rds_proxy_idle_timeout
	rds_proxy_tls				= var.rds_proxy_tls
	rds_proxy_role_arn			= var.rds_proxy_role_arn
	rds_proxy_vpc_subnets		= var.rds_proxy_vpc_subnets
	rds_proxy_auth_scheme		= var.rds_proxy_auth_scheme
	rds_proxy_auth_description	= var.rds_proxy_auth_description
	rds_proxy_auth_iam			= var.rds_proxy_auth_iam
	rds_proxy_tags				= var.rds_proxy_tags
	rds_proxy_tg_connection_borrow_timeout		= var.rds_proxy_tg_connection_borrow_timeout
	rds_proxy_tg_max_idle_connections_percent	= var.rds_proxy_tg_max_idle_connections_percent
	rds_proxy_tg_max_connections_percent		= var.rds_proxy_tg_max_connections_percent
	rds_proxy_target_db_identifier	= var.rds_proxy_target_db_identifier
}