cf_oai_comment	= "OAI for schrute S3 UI Bucket dev"

s3b_short_name					= "schrute-serverless-ui"
s3b_environment					= "dev"
s3b_logging_bucket_name			= "franklin-dev-s3-access-logs"
s3b_logging_bucket_base_prefix	= "schrute-ui"
s3b_acl							= "private"
s3b_tags = {
	"ApplicationName"		= "schrute"
	"Automated"				= "True"
	"BackupPlan"			= "None"
	"CostCenter"			= "Operations"
	"CreatedBy"				= "DevOps"
	"CreatedOn"				= "09022024"
	"DataClassification"	= "None"
	"Department"			= "HMS"
	"Infrastructure"		= "False"
	"LastUpdated"			= "09022024"
	"TechStack"				= "Angular"
	"Usage"					= "Project"
	"Version"				= "1.0"
}
s3b_cloudfront_oai_policy		= true

cf_aliases							= ["dev-schrute-ui.franklinmadisonds.com"]
cf_logging_config_bucket			= "DUMMY_VALUE_TO_BE_UPDATED"
cf_logging_config_prefix			= "DUMMY_VALUE_TO_BE_UPDATED_NEXT_ONE_ALSO"
cf_logging_config_include_cookies	= true
cf_http_version						= "http2"
cf_enabled							= true
cf_is_ipv6_enabled					= true
cf_default_root_object				= "index.html"
cf_comment							= "schrute UI App dev"
cf_dcb_allowed_methods				= ["GET", "HEAD", "OPTIONS", "PUT", "POST", "PATCH", "DELETE"]
cf_dcb_cached_methods				= ["GET", "HEAD", "OPTIONS"]
cf_dcb_compress						= true
cf_dcb_viewer_protocol_policy		= "redirect-to-https"
cf_dcb_default_ttl					= 300
cf_dcb_min_ttl						= 300
cf_dcb_max_ttl						= 300
cf_dcb_fv_query_string				= false
cf_dcb_fv_c_forward					= "none"
cf_vc_acm_certificate_arn			= "arn:aws:acm:us-east-1:116762271881:certificate/e9b002db-d44f-4e40-bf62-3ff34e95bf89"
cf_vc_minimum_protocol_version		= "TLSv1.2_2021"
cf_vc_ssl_support_method			= "sni-only"
cf_price_class						= "PriceClass_100"
cf_r_g_restriction_type				= "whitelist"
cf_r_g_locations					= ["IN", "US"]
cf_cer_error_caching_min_ttl		= "30"
cf_cer_error_code					= "403"
cf_cer_response_code				= "200"
cf_cer_response_page_path			= "/index.html"
cf_tags = {
	"ApplicationName"		= "schrute"
	"Automated"				= "True"
	"BackupPlan"			= "None"
	"CostCenter"			= "Operations"
	"CreatedBy"				= "DevOps"
	"CreatedOn"				= "09022024"
	"DataClassification"	= "None"
	"Department"			= "HMS"
	"Infrastructure"		= "False"
	"LastUpdated"			= "09022024"
	"TechStack"				= "AWS"
	"Usage"					= "Project"
	"Version"				= "1.0"
}

r53_zone_id	= "Z04314328KDEDCB3P6MU"
r53_name	= "dev-schrute-ui.franklinmadisonds.com"
r53_type	= "CNAME"
r53_ttl		= 300