iam_policy_name			= "lasso-rds-proxy-policy-dev"
iam_policy_tags			= {
		"Department": "LSO"
        "LastUpdated": "07142022"
        "CostCenter":  "FMG"
        "CreatedOn": "07142022"
        "DataClassification": "Low"
        "Infrastructure": "False"
        "Usage":"Project"
        "Version": "1.0"
        "ApplicationName": "Lasso"
        "TechStack": "None"
        "Automated": "True"
        "BackupPlan": "None"
        "CreatedBy": "sbose"
    }
lasso_rds_proxy_policy	= "true"
lasso_rds_dbuser_arn	= "arn:aws:rds-db:us-east-1:116762271881:dbuser:prx-0ca764ba4d64642d3/*"
iam_policy_desc			= "Lasso Access RDS Proxy Dev"