iam_policy_name				= "bottomsup-secrets-manager-policy-dev"
iam_policy_tags				= {
		"Department": "BottomsUp"
        "LastUpdated": "06262023"
        "CostCenter":  "FMG"
        "CreatedOn": "01242023"
        "DataClassification": "Low"
        "Infrastructure": "False"
        "Usage":"Project"
        "Version": "1.0"
        "ApplicationName": "BottomsUp"
        "TechStack": "AWS"
        "Automated": "True"
        "BackupPlan": "None"
        "CreatedBy": "mmadhu"
    }
lasso_secrets_mgr_policy	= "true"
iam_policy_desc				= "BottomsUp Access Secret Manager Dev"