iam_policy_name			= "bottomsup-logger-policy-dev"
iam_policy_tags			= {
		"Department": "BottomsUp"
        "LastUpdated": "06262023"
        "CostCenter":  "FMG"
        "CreatedOn": "01242023"
        "DataClassification": "Low"
        "Infrastructure": "False"
        "Usage":"Project"
        "Version": "1.0"
        "ApplicationName": "BottomsUp"
        "TechStack": "AWS"
        "Automated": "True"
        "BackupPlan": "None"
        "CreatedBy": "mmadhu"
    }
lasso_logger_policy		= "true"
lasso_log_group_arn		= "arn:aws:logs:us-east-1:116762271881:*"
iam_policy_desc			= "BottomsUp Logger Policy Dev"