- hosts: all
  remote_user: ansible
  become: yes
  become_user: root
  tasks:
  - name: "Install python3.8"
    become: yes
    yum:
      name: python38
      state: latest
  - name: Install SSM agent package
    ansible.builtin.dnf:
      name: 'https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm'
      state: present
