- hosts: all
  remote_user: ansible
  become: yes
  become_user: root
  tasks:
  - name: "Install Nginx"
    become: yes
    yum:
      name: nginx
      state: latest
  - name: Start service nginx, if not started
    service:
      name: nginx
      state: started