# ansible-playbook ssh_fix_dev.yml -u ansible --private-key="~/.ssh/ansible.pem"
- hosts: ssh_fix_dev
  remote_user: ansible
  become: yes
  become_user: root
  tasks:
  - name: "Backup the current sshd config"
    shell: |
        cp /etc/ssh/sshd_config /etc/ssh/sshd_config_backup_ssh_fix
  - name: "Set AllowTcpForwarding to no"
    shell: |
        sed -i 's/#AllowTcpForwarding yes/AllowTcpForwarding no/' /etc/ssh/sshd_config
  - name: "Disable system-wide crypto policy"
    shell: |
        sed -i 's/# CRYPTO_POLICY=/CRYPTO_POLICY=/' /etc/sysconfig/sshd
  - name: "Add Ciphers, KexAlgorithms and MACs"
    shell: |
        echo -e "\nCiphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com" >> /etc/ssh/sshd_config
        echo "KexAlgorithms diffie-hellman-group-exchange-sha256,curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521" >> /etc/ssh/sshd_config
        echo "MACs hmac-sha2-256,hmac-sha2-512,umac-64@openssh.com,umac-128@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-md5-etm@openssh.com,hmac-md5-96-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com" >> /etc/ssh/sshd_config
  - name: "Restart sshd"
    shell: |
        systemctl restart sshd