- hosts: all
  become: yes
  remote_user: ansible
  become_user: root
  tasks:
  - name: stop nginx
    service:
      name: nginx
      state: stopped
  - name: ensure nginx is not installed
    yum:
      name: ['nginx']
      state: absent