iam_policy_name			= "marketing-kms-policy-pci"
iam_policy_tags			= {
	"Department": "MKT"
	"LastUpdated": "06262024"
	"CostCenter": "FMG"
	"CreatedOn": "06262024"
	"DataClassification": "PCI"
	"Infrastructure": "False"
	"Usage":"Project"
	"Version": "1.0"
	"ApplicationName": "Marketing"
	"TechStack": "AWS"
	"Automated": "True"
	"BackupPlan": "None"
	"CreatedBy": "DevOps"
    }
marketing_kms_policy	    = "true"
iam_policy_desc				= "Marketing KMS Access Policy PCI"