iam_policy_name			= "marketing-dynamodb-policy-pci"
iam_policy_tags			= {
    "Department": "MKT"
	"LastUpdated": "06262024"
	"CostCenter": "FMG"
	"CreatedOn": "06262024"
	"DataClassification": "PCI"
	"Infrastructure": "False"
	"Usage":"Project"
	"Version": "1.0"
	"ApplicationName": "Marketing"
	"TechStack": "AWS"
	"Automated": "True"
	"BackupPlan": "None"
	"CreatedBy": "DevOps"
    }
marketing-dynamodb-policy	= "true"
iam_policy_desc				= "Marketing DynamoDB Access Policy PCI"