iam_policy_name			= "bottomsup-rds-proxy-policy-dev"
iam_policy_tags			= {
		"Department": "BottomsUp"
        "LastUpdated": "06262023"
        "CostCenter":  "FMG"
        "CreatedOn": "01242023"
        "DataClassification": "Low"
        "Infrastructure": "False"
        "Usage":"Project"
        "Version": "1.0"
        "ApplicationName": "BottomsUp"
        "TechStack": "AWS"
        "Automated": "True"
        "BackupPlan": "None"
        "CreatedBy": "mmadhu"
    }
lasso_rds_proxy_policy	= "true"
lasso_rds_dbuser_arn	= "arn:aws:rds-db:us-east-1:116762271881:dbuser:prx-0ca764ba4d64642d3/*"
iam_policy_desc			= "BottomsUp Access RDS Proxy Dev"