domain_name = "marketingservices-athena-mt.franklinmadisonds.com"
validation = "DNS"
tags = {
	"ApplicationName"		= "AthenaNextgen2.0"
	"Automated"				= "True"
	"BackupPlan"			= "None"
	"CostCenter"			= "FMG"
	"CreatedBy"				= "DevOps"
	"CreatedOn"				= "06202024"
	"DataClassification"	= "PCI"
	"Department"			= "ANG2"
	"Infrastructure"		= "False"
	"LastUpdated"			= "06202024"
	"TechStack"				= "AWS"
	"Usage"					= "Project"
	"Version"				= "1.0"
}