// domain_name = "hermes-dr.franklinmadisonds.com"
// validation = "DNS"
// tags = {
	// "ApplicationName"		= "Hermes2.0"
	// "Automated"				= "True"
	// "BackupPlan"			= "None"
	// "CostCenter"			= "Operations"
	// "CreatedBy"				= "DevOps"
	// "CreatedOn"				= "02232024"
	// "DataClassification"	= "None"
	// "Department"			= "HMS2"
	// "Infrastructure"		= "False"
	// "LastUpdated"			= "02232024"
	// "TechStack"				= "AWS"
	// "Usage"					= "Project"
	// "Version"				= "1.0"
// }