iam_policy_name		= "lasso-kms-policy-pci"
iam_policy_tags		= {
		"Department": "LSO"
		"LastUpdated": "06152023"
		"CostCenter": "FMG"
		"CreatedOn": "06152023"
		"DataClassification": "Low"
		"Infrastructure": "False"
		"Usage": "Project"
		"Version": "1.0"
		"ApplicationName": "Lasso"
		"TechStack": "None"
		"Automated": "True"
		"BackupPlan": "None"
		"CreatedBy": "sbose"
	}
lasso_kms_policy	= "true"
iam_policy_desc		= "Lasso KMS Policy PCI"