domain_name = "dr.insuranceapps.franklinmadisonds.com"
validation = "DNS"
tags = {
    "ApplicationName" = "InsuranceApps"
	"Automated" = "True"
	"BackupPlan" = "None"
	"CostCenter" = "FMG"
	"CreatedBy" = "mfaizudeen"
	"CreatedOn" = "01162023"
	"DataClassification" = "Low"
	"Department" = "IAP"
	"Infrastructure" = "False"
	"LastUpdated" = "01162023"
	"TechStack" = "AWS"
	"Usage" = "Project"
	"Version" = "1.0"
    "Name" = "UI Apps dr"
}