iam_policy_name			= "lasso-vpc-access-policy-dev"
iam_policy_tags			= {
		"Department": "LSO"
        "LastUpdated": "07142022"
        "CostCenter":  "FMG"
        "CreatedOn": "07142022"
        "DataClassification": "Low"
        "Infrastructure": "False"
        "Usage":"Project"
        "Version": "1.0"
        "ApplicationName": "Lasso"
        "TechStack": "None"
        "Automated": "True"
        "BackupPlan": "None"
        "CreatedBy": "sbose"
    }
lasso_vpc_access_policy	= "true"
iam_policy_desc			= "Lasso Lambda VPC Access Policy Dev"