hermes_email_archival_cuscommupload_api_bool = true
lambda_function_name = "hermes-email-archival-cuscommupload-api-dev"
role = "arn:aws:iam::116762271881:role/hermes-lambda-role-dev"
description = "Hermes Email Archival & Customer Communication Upload API Dev"
env_variables = {
	"CUSCOMMUPLOAD_API_URL"		= "https://dev.mtservicesapps.franklinmadisonds.com/batchintegration-web/rest/cusCommUploadProcess"
	"EMAIL_ARCHIVAL_API_URL"	= "https://dev.mtservicesapps.franklinmadisonds.com/batchintegration-web/rest/emailArchiveProcess"
}
tags = {
	"ApplicationName"		= "Hermes2.0"
	"Automated"				= "True"
	"BackupPlan"			= "None"
	"CostCenter"			= "Operations"
	"CreatedBy"				= "DevOps"
	"CreatedOn"				= "11232023"
	"DataClassification"	= "None"
	"Department"			= "HMS2"
	"Infrastructure"		= "False"
	"LastUpdated"			= "11232023"
	"TechStack"				= "Python"
	"Usage"					= "Project"
	"Version"				= "1.0"
}
memory_size = 128
ephemeral_storage_size = 512
timeout = 10
subnets = ["subnet-0734d8f28467d319f","subnet-06291ceaa523f684c"]
security_groups = ["sg-03ec84b14631c5168"]
reserved_concurrent_executions = -1
publish = false
runtime = "python3.11"
handler = "hermes-email-archival-cuscommupload-api.lambda_handler"
filename = "py/hermes-email-archival-cuscommupload-api.zip"
package_type = "Zip"
source_code_hash = "py/hermes-email-archival-cuscommupload-api.zip"

schedule_group_name = "hermes-serverless-scheduled-jobs-dev"
schedule_name = "hermes-cuscommupload-api-schedule-dev"
schedule2_name = "hermes-email-archival-api-schedule-dev"
schedule_target_role_arn = "arn:aws:iam::116762271881:role/hermes-ecs-task-execution-role-dev"