domain_name = "qa-forecast-mt.franklinmadisonds.com"
validation = "DNS"
tags = {
    "ApplicationName"		= "InsuranceApps"
	"Automated"				= "True"
	"BackupPlan"			= "None"
	"CostCenter"			= "FMG"
	"CreatedBy"				= "DevOps"
	"CreatedOn"				= "08212024"
	"DataClassification"	= "Low"
	"Department"			= "IAPPS"
	"Infrastructure"		= "False"
	"LastUpdated"			= "08212024"
	"TechStack"				= "AWS"
	"Usage"					= "Project"
	"Version"				= "1.0"
    }